spring.application.name=skillbackend
spring.datasource.url=jdbc:mysql://localhost:3306/skillswap
spring.datasource.username=root
spring.datasource.password=sabari129

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
